#!/bin/bash
# --------------------------------------------------------------------------
# Uptime-Manager: default implementation of um_set_halt
#
# This script will
#   - schedule a shutdown if seconds until halt are < 600 (10 minutes)
#   - reschedule "um_ctrl.py set halt" otherwise
# 
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/uptime-manager
#
# --------------------------------------------------------------------------

# use local override if available
if type -p um_set_halt.local > /dev/null; then
  um_set_halt.local "$@"
  exit $?
fi

if [ "$UID" != 0 ]; then
  # test-mode
  echo "halt-time:           $1"
  echo "halt-time (seconds): ${2%.*}"
  echo "seconds until halt:  $3"
  echo "database-name:       $4"
else
  # production-mode
  systemctl stop um_set_halt.timer  # remove existing timer (if active)
  echo "scheduling shutdown at $1"
  systemd-run --on-calendar="$1" --unit=um_set_halt /sbin/halt -p
fi
